package eu.tgx03.ffmpeg;

import java.util.List;

/**
 * Custom exception class used to represent errors related to FFMpeg operations.
 * <p>
 * This exception is specifically designed to capture and store
 * the output generated by FFMpeg during its execution.
 */
public class FFMPEGException extends RuntimeException {

    /**
     * The list holding the FFMpeg output
     */
    private final List<String> ffmpegOutput;

    /**
     * Constructs a new FFMPEGException with the specified detail message and FFMpeg output data.
     *
     * @param message The detail message providing information about the exception.
     * @param ffmpegOutput A list of strings representing the output from FFMpeg.
     */
    public FFMPEGException(String message, List<String> ffmpegOutput) {
        super(message);
        this.ffmpegOutput = ffmpegOutput;
    }

    /**
     * Retrieves the list of FFMpeg output messages.
     *
     * This method returns the captured output generated by FFMpeg during its execution.
     * The output may include information, status messages, warnings, or errors produced
     * by the FFMpeg process.
     *
     * @return A list of strings representing the output from FFMpeg.
     */
    public List<String> getFFMPEGOutput() {
        return this.ffmpegOutput;
    }
}
